default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: users-api-development

test:
  <<: *default
  database: users-api-test

production:
  <<: *default
  database: users-api-production
